### ISSUE TITLE
[FR]: 画像の表示速度改善

### ISSUE THREAD

**Issue by ka10take** [yoshikawacityfc/yoshikawacityfc#99]
### 既存の課題がありませんか？

- [X] 既存の課題を検索してみました

### 問題を説明する

画像の表示速度が遅い時がある。

### 解決策を説明する

pngやjpgファイルを全てwebpに置き換える。

**Comment by tatsutakein** [comment]
なんかいい感じに軽量にしてくれるサービスあったよね？名前忘れてしまった。。

**Comment by ka10take** [comment]
以前勉強会で話してたやつですよね？？
ここら辺だと思います〜

https://www.cloudflare.com/ja-jp/products/cloudflare-images/
https://cloudinary.com/

**Comment by tatsutakein** [comment]
それだ！
もしそれらを使うとしたら無料枠がある Cloudinary かな〜

でも単純に webp に変えたりするだけでもかなりカイゼンできそう？🤔

**Comment by ka10take** [comment]
ですね〜！webpに変更するだけでわりと速度改善できると思いますので、一旦やってみます👍
